## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(Lml0QI+7bzNMpRqvsBEfcvob65y4Zk5D)  #web
      client-secret: ENC(Lml0QI+7bzNMpRqvsBEfcvob65y4Zk5D)  #web
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /user/third/**
        - /mauth/**
        - /verify/**
        - /reg/**
        - /log/save
        - /v1/**
        - /user/userId/**
        - /mobile/sendsms/**

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(w7Wf2el9+CdHNglsKc2SKA==)
    password: ENC(tExkneOk2oveLQsQ473T7AL+dJi483eU)
    url: jdbc:mysql://${MYSQL-HOST:msdp-mysql}:${MYSQL-PORT:4306}/${MYSQL-DB:t_upm}?characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

# 文件系统 (提供测试环境，不要乱传)
minio:
  url: http://minio.msdp.com:9000
  access-key: ENC(VB7z4nTk65ZNG5zT4t+w/iR97K8RsTt0) #msdp.file
  secret-key: ENC(dJ6vHXQLIwVmW0HT85Dya03VSFsVWy4E) #msdp.file123

# Logger Config
logging:
  level:
    com.iyysoft.msdp.dp.sys.mapper: debug

# 租户表维护
iyysoft:
  user:
    default_role: 1
  tenant:
    column: tenant_id
    tables:
      - sys_user
      - sys_role
      - sys_dept
      - sys_log
      - sys_third
      - sys_dict
      - sys_dict_item
      - sys_log
