security:
  encode:
    # 前端密码密钥，必须16位
    key: 'iyysoft.msdp.123'
  oauth2:
    client:
      client-id: msdp.workmanager
      client-secret: msdp.workmanager
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /user/third/**
        - /mauth/**
        - /verify/**
        - /reg/**
        - /log/save
        - /v1/**
        - /v2/**
        - /user/userId/**
        - /mobile/sendsms/**
        - /**

# 不校验验证码终端
ignore:
  clients:
    - test
  swagger-providers:
    - ${AUTH-HOST:msdp-auth}
    - ${TX-MGR-HOST:msdp-tx-manager}
# 数据源
spring:
  rabbitmq:
    host: 47.97.20.197
    port: 5677
    username: wkvv
    password: wkvv123
    connection-timeout: 30000
    template:
      receive-timeout: 3000
    cache:
      channel:
        size: 100
    virtual-host: msdp
    listener:
      wkAttend:
        queue:
          name: wkAttendQueue
          durable: ture
        exchange:
          name: wkAttendExchange
          durable: ture
          type: direct
          ignoreDeclarationExceptions:
        key: wkAttendKey
      wkAttendResult:
        queue:
          name: wkAttendResultQueue
          durable: ture
        exchange:
          name: wkAttendResultExchange
          durable: ture
          type: direct
          ignoreDeclarationExceptions:
        key: wkAttendResultKey
  datasource:
    dynamic:
      primary: master_
      datasource:
        master_:  #使用vip 数据源
          username: ms_wkvv
          password: msWKVV_123
          url: jdbc:mysql://47.97.222.54:4306/ms_wkvv?characterEncoding=utf8&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        sqlserver:
          username: wp_sa_read
          password: ys_WinsheRDS
          url: jdbc:sqlserver://rds5y5l2x7n04c5ez2l1o.sqlserver.rds.aliyuncs.com:3433;DatabaseName=winshe_platform;integratedSecurity=false;
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          #username: sa_chim
          #password: Winshe87778111
          type: com.zaxxer.hikari.HikariDataSource
config:
  wkvv:
    saas:
      #      saas相关参数配置
      webapiurl: http://api.91jtg.com:8020
      webauthurl: http://app.91jtg.com
      publictokenname: z99cszh
      publictokenpwd: 123456