## spring security 配置
security:
  oauth2:
    client:
      client-id: msdp.workmanager
      client-secret: msdp.workmanager
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /user/info/*
        - /user/third/**
        - /mauth/**
        - /verify/**
        - /reg/**
        - /log/save
        - /v1/**
        - /v2/**
        - /user/userId/**
        - /mobile/sendsms/**
        - /**

# 数据源
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${MYSQL-USER:t_upm}
#    password: ${MYSQL-PWD:base.C1upm}
#    url: jdbc:mysql://${MYSQL-HOST:msdp-mysql}:${MYSQL-PORT:9306}/${MYSQL-DB:t_upm}?characterEncoding=utf8&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

# 数据源
spring:
  datasource:
    dynamic:
      primary: master_
      datasource:
        master_:  #使用vip 数据源
          username: db_manager
          password: 123!QWEasd
          url: jdbc:mysql://${MYSQL-HOST:msdp-mysql}:${MYSQL-PORT:9306}/${MYSQL-DB:ms_wkvv}?characterEncoding=utf8&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        slave_:  #使用vip 数据源
          username: db_manager
          password: 123!QWEasd
          url: jdbc:mysql://${MYSQL-HOST:read-msdp-mysql}:${MYSQL-PORT:9306}/${MYSQL-DB:ms_wkvv}?characterEncoding=utf8&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        sqlserver:
          username: wpbk_sa_read
          password: ws_WinsheRDSbk
          url: jdbc:sqlserver://rds5y5l2x7n04c5ez2l1o.sqlserver.rds.aliyuncs.com:3433;DatabaseName=winshe_platform_bk;integratedSecurity=false;
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          #username: sa_chim
          #password: Winshe87778111
          type: com.zaxxer.hikari.HikariDataSource
        #postgresql:
        #oracle:

  rabbitmq:
    host: 119.3.109.7
    port: 5672
    username: snap
    password: snap123
    connection-timeout: 30000
    template:
      receive-timeout: 3000
    cache:
      channel:
        size: 100
    virtual-host: SaaS
    listener:
      wkAttend:
        queue:
          name: wkAttendQueue
          durable: ture
        exchange:
          name: wkAttendExchange
          durable: ture
          type: direct
          ignoreDeclarationExceptions:
        key: wkAttendKey
      wkAttendResult:
        queue:
          name: wkAttendResultQueue
          durable: ture
        exchange:
          name: wkAttendResultExchange
          durable: ture
          type: direct
          ignoreDeclarationExceptions:
        key: wkAttendResultKey

config:
  wkvv:
    saas:
      #      saas相关参数配置
      webapiurl: http://api.91jtg.com:8020
      webauthurl: http://app.91jtg.com
      publictokenname: z99cszh
      publictokenpwd: 123456


# 文件系统 (提供测试环境，不要乱传)#msdp.file123
minio:
  url: http://minio.msdp.com:9000
  access-key: msdp.file
  secret-key: msdp.file123

## Logger Config
#logging:
#  level:
#    com.iyysoft.msdp.dp.sys: debug

# 租户表维护
iyysoft:
  user:
    default_role: 1
  tenant:
    column: tenant_id
    tables:
      - user
      - role
      - org
      - log_oper
      - user_third
      - sys_dict
      - sys_dict_item
      - sys_log
