## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(b9MKPGjqbWelPh8nYouPyNbCCY9ExiZy)    #act
      client-secret: ENC(b9MKPGjqbWelPh8nYouPyNbCCY9ExiZy)    #act
      scope: server
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/service/**'
        - '/editor-app/**'
        - '/task/view/*'
        - '/process/resource/**'
        - '/modeler.html'
        - '/ws/**'
spring:
  autoconfigure:
    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
  activiti:
    check-process-definitions: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(w7Wf2el9+CdHNglsKc2SKA==)
    password: ENC(tExkneOk2oveLQsQ473T7AL+dJi483eU)
    url: jdbc:mysql://${MYSQL-HOST:122.112.234.91}:${MYSQL-PORT:3306}/${MYSQL-DB:iyysoft_ac}?characterEncoding=utf8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true

# 租户表维护
iyysoft:
  tenant:
    column: tenant_id
    tables:
      - oa_leave_bill
